- resources/public/contracts/src/ethlanceDB.sol
- resources/public/contracts/src/ethlanceSetter.sol
- resources/public/contracts/src/mortal.sol
- resources/public/contracts/src/sponsorRelated.sol
ethlanceSetter.sol:3:1: Error: Source "Ownable.sol" not found: Unknown exception in read callback.
import "Ownable.sol";
^-------------------^
ethlanceDB.sol:3:1: Error: Source "Ownable.sol" not found: Unknown exception in read callback.
import "Ownable.sol";
^-------------------^
ethlanceSetter.sol:3:1: Error: Source "Ownable.sol" not found: Unknown exception in read callback.
import "Ownable.sol";
^-------------------^
ethlanceDB.sol:3:1: Error: Source "Ownable.sol" not found: Unknown exception in read callback.
import "Ownable.sol";
^-------------------^
ethlanceSetter.sol:3:1: Error: Source "Ownable.sol" not found: Unknown exception in read callback.
import "Ownable.sol";
^-------------------^
ethlanceDB.sol:3:1: Error: Source "Ownable.sol" not found: Unknown exception in read …
> Fix import errors

- src/cljs/ethlance/events.cljs
- src/cljs/ethlance/web3_fx.cljs
> Changes ethlance initialization to ask for initial ethereum provider

- project.clj
- src/cljs/ethlance/web3_fx.cljs
- Fixes EIP-1102 deprecated authorization
- Replaces cemerick.piggieback with updated nrepl.piggieback
> Fixes Issue #51

- resources/public/less/component/icon.less
- resources/public/less/component/main-layout.less
- resources/public/less/component/mobile-navigation-bar.less
- resources/public/less/component/mobile-search-filter.less
- resources/public/less/component/search-input.less
- resources/public/less/component/select-input.less
- resources/public/less/components.less
- resources/public/less/mixin/main-container.less
- resources/public/less/mixin/sidebar.less
- resources/public/less/mixins.less
- resources/public/less/page/jobs.less
- src/ui/ethlance/ui/component/main_layout.cljs
- src/ui/ethlance/ui/component/mobile_navigation_bar.cljs
- src/ui/ethlance/ui/component/mobile_search_filter.cljs
- src/ui/ethlance/ui/component/select_input.cljs
- src/ui/ethlance/ui/page/jobs.cljs
A lot of responsive components were added, and the main layout has been made completely responsive. The rest of the pages will be a matter of re-using these components. 
Still trying to figure out how to make the chip search input more responsive, this is something we'll have to discuss. I have some ideas, but maybe there are some better alternatives.
> Jobs page 69

- resources/public/images/svg/checkbox.svg
- resources/public/less/component/checkbox.less
- resources/public/less/component/main-layout.less
- resources/public/less/component/radio-select.less
- resources/public/less/component/select-input.less
- resources/public/less/component/tabular-layout.less
- resources/public/less/components.less
- resources/public/less/page/sign-up.less
- src/ui/ethlance/ui/component/checkbox.cljs
- src/ui/ethlance/ui/component/radio_select.cljs
- src/ui/ethlance/ui/component/search_input.cljs
- src/ui/ethlance/ui/component/select_input.cljs
- src/ui/ethlance/ui/component/tabular_layout.cljs
- src/ui/ethlance/ui/page/devcard.cljs
- src/ui/ethlance/ui/page/sign_up.cljs
- Main sign-up page for candidates, employers, and arbiters
- Implements #77 
- Adds checkbox component
- Includes responsive fixes for tabular layout
> Sign up page 77

- resources/public/less/component/carousel.less
- resources/public/less/component/circle-button.less
- resources/public/less/component/rating.less
- resources/public/less/component/tabular-layout.less
- resources/public/less/components.less
- resources/public/less/page/me.less
- resources/public/less/page/profile.less
- resources/public/less/pages.less
- src/shared/ethlance/shared/routes.cljs
- src/ui/ethlance/ui/component/carousel.cljs
- src/ui/ethlance/ui/component/circle_button.cljs
- src/ui/ethlance/ui/page/jobs.cljs
- src/ui/ethlance/ui/page/profile.cljs
- src/ui/ethlance/ui/pages.cljs
A bit more work on the carousel needs to be done for mobile, but what is currently there is already functional
> My profile page 76

- Makefile
- resources/public/less/base/font.less
- resources/public/less/component/carousel.less
- resources/public/less/component/table.less
- resources/public/less/mixin/table-button-listing.less
- resources/public/less/mixin/title-header.less
- resources/public/less/mixins.less
- resources/public/less/page/job-detail.less
- resources/public/less/page/profile.less
- resources/public/less/pages.less
- src/ui/ethlance/ui/component/carousel.cljs
- src/ui/ethlance/ui/page/job_detail.cljs
- src/ui/ethlance/ui/page/profile.cljs
- src/ui/ethlance/ui/pages.cljs
> Job detail page 68

- resources/public/less/page/new-job.less
- resources/public/less/pages.less
- src/ui/ethlance/ui/page/new_job.cljs
- src/ui/ethlance/ui/pages.cljs
Fixes #75
Fixes #73 (same page, different radio option)
> New job page 75

- resources/public/less/page/new-invoice.less
- resources/public/less/pages.less
- src/shared/ethlance/shared/routes.cljs
- src/ui/ethlance/ui/page/new_invoice.cljs
- src/ui/ethlance/ui/pages.cljs
> Finished Invoice Page

- resources/public/less/page/invoice-detail.less
- resources/public/less/pages.less
- src/shared/ethlance/shared/routes.cljs
- src/ui/ethlance/ui/page/invoice_detail.cljs
- src/ui/ethlance/ui/pages.cljs
> Finished Invoice Detail Page

- resources/public/less/component/rating.less
- resources/public/less/page/arbiters.less
- src/ui/ethlance/ui/page/arbiters.cljs
> Finished Arbiters Page

- resources/public/less/page/candidates.less
- src/ui/ethlance/ui/page/candidates.cljs
> Finished candidates page (mirror of arbiter's page)

- src/ui/ethlance/ui/component/button.cljs
- src/ui/ethlance/ui/component/carousel.cljs
- src/ui/ethlance/ui/component/chat.cljs
- src/ui/ethlance/ui/component/checkbox.cljs
- src/ui/ethlance/ui/component/circle_button.cljs
- src/ui/ethlance/ui/component/currency_input.cljs
- src/ui/ethlance/ui/component/email_input.cljs
- src/ui/ethlance/ui/component/ethlance_logo.cljs
- src/ui/ethlance/ui/component/icon.cljs
- src/ui/ethlance/ui/component/inline_svg.cljs
- src/ui/ethlance/ui/component/main_layout.cljs
- src/ui/ethlance/ui/component/main_navigation_bar.cljs
- src/ui/ethlance/ui/component/main_navigation_menu.cljs
- src/ui/ethlance/ui/component/profile-image.cljs
- src/ui/ethlance/ui/component/radio_select.cljs
- src/ui/ethlance/ui/component/rating.cljs
- src/ui/ethlance/ui/component/search_input.cljs
- src/ui/ethlance/ui/component/select_input.cljs
- src/ui/ethlance/ui/component/table.cljs
- src/ui/ethlance/ui/component/tabular_layout.cljs
- src/ui/ethlance/ui/component/tag.cljs
- src/ui/ethlance/ui/component/text_input.cljs
- src/ui/ethlance/ui/component/textarea_input.cljs
Includes doc strings for all of the major ethlance components
> Component documentation 83

- resources/public/less/base/layout.less
- resources/public/less/component/splash-layout.less
- resources/public/less/component/splash-navigation-bar.less
- src/ui/ethlance/ui/component/splash_layout.cljs
> Finished all styling changes for splash layout

- resources/public/less/base/color.less
- resources/public/less/component/currency-input.less
- resources/public/less/component/main-layout.less
- resources/public/less/component/select-input.less
- resources/public/less/component/text-input.less
- resources/public/less/page/arbiters.less
- src/ui/ethlance/ui/page/arbiters.cljs
- Refinement of Issue #64
- select-input secondary styling has been fixed to match design
- removed filter section 'Payment Types'
- increased header navigation bar height to match design
Branch will be merged with newlance so I continue work on other issues and to note any regressions when working on other pages
> Refinement arbiters page 64

- resources/public/less/page/candidates.less
- resources/public/less/page/employers.less
- resources/public/less/pages.less
- src/ui/ethlance/ui/page/employers.cljs
- src/ui/ethlance/ui/pages.cljs
- Implements #104 
- Certain elements of what's required on the page are unavailable, need input from @madvas
> Employers page 104

- resources/public/less/page/invoice-detail.less
- src/ui/ethlance/ui/page/invoice_detail.cljs
> Finished Invoice Detail Refinement

- dev/server/cljs/user.cljs
- project.clj
- src/server/ethlance/server/core.cljs
- src/server/ethlance/server/graphql/mutations/sign_in.cljs
- src/server/ethlance/server/graphql/resolver.cljs
- src/shared/ethlance/shared/graphql/schema.cljs
- src/ui/ethlance/ui/config.cljs
- src/ui/ethlance/ui/core.cljs
- src/ui/ethlance/ui/events.cljs
- src/ui/ethlance/ui/fxs.cljs
Implements in server :
- a sign-in graphql mutation
- a session express middleware
- a graphql-resolver wrapper for require-auth
Implements in UI : 
- sign in events and fxs
> Fix #90 Sign in functionality

- resources/public/images/svg/checkbox.svg
- resources/public/less/component/checkbox.less
- resources/public/less/component/icon.less
- resources/public/less/component/main-layout.less
- resources/public/less/component/text-input.less
- resources/public/less/mixin/input.less
- resources/public/less/page/sign-up.less
- src/ethlance/ui/component/icon.cljs
- src/ethlance/ui/component/select_input.cljs
- src/ethlance/ui/page/sign_up.cljs
- Fixes #77 
- Increased width of main-navigation-bar
- Fixed color scheme on upload-image button and select-input component
- Fixed Checkbox Component to match design
- Removed placeholder text where necessary
- Removed Payment Type options for arbiter sign up
> Refinement sign up page 77

- resources/public/less/base/font.less
- resources/public/less/base/layout.less
- resources/public/less/component/main-layout.less
- resources/public/less/component/mobile-navigation-bar.less
- resources/public/less/component/splash-layout.less
- resources/public/less/component/splash-navigation-bar.less
- resources/public/less/page/job-detail.less
- src/ethlance/ui/component/mobile_navigation_bar.cljs
- src/ethlance/ui/page/job_detail.cljs
- Fixes #68 
- Fixes Job Detail Description Font
- Fixed data scroll header styling bleeding into job detail
- Fixed funding ticket styling
- Decreased size of table navigation buttons
- Broken Mobile Layout will be fixed in #107 
- Fixed inputs and font sizes for mobile and tablet
- Implemented mobile-navigation-bar account information (slightly different from design site)
> Refinement job detail page 68

- src/cljs/ethlance/web3_fx.cljs
Fixes #51 
Tested with advanced compilation, dialog is showing correctly.
> Hotfix for Privacy Mode with Advanced Compilation

- resources/public/less/page/new-invoice.less
- src/ethlance/ui/page/new_invoice.cljs
> Refinement new invoice page 74

- resources/public/less/component/mobile-search-filter.less
- resources/public/less/page/jobs.less
- src/ethlance/ui/component/text_input.cljs
- src/ethlance/ui/page/jobs.cljs
> Finished job page refinement

- resources/public/less/page/job-contract.less
- src/ethlance/ui/page/job_contract.cljs
> Finished Job Contracts Page Refinment Work

- resources/public/less/component/main-layout.less
> Main layout fix 132

- resources/public/less/component/search-input.less
- resources/public/less/component/table.less
- resources/public/less/page/job-detail.less
- resources/public/less/page/new-invoice.less
- src/ethlance/ui/component/search_input.cljs
- src/ethlance/ui/page/profile.cljs
- fixed strange outline issue
- chip select now scrolls through results instead of showing the first 4 results
- @madvas we should discuss whether we should include a more intelligent search algorithm, it's pretty naive right now.
- fixed minor margin issues
- found a few other issues to fix in the new scrollable component
> Finished Minor Fixes

- resources/public/index.html
- resources/public/less/page/how-it-works.less
- resources/public/less/pages.less
- src/ethlance/shared/routes.cljs
- src/ethlance/ui/component/button.cljs
- src/ethlance/ui/component/checkbox.cljs
- src/ethlance/ui/component/circle_button.cljs
- src/ethlance/ui/component/ethlance_logo.cljs
- src/ethlance/ui/component/icon.cljs
- src/ethlance/ui/component/inline_svg.cljs
- src/ethlance/ui/component/main_layout.cljs
- src/ethlance/ui/component/main_navigation_bar.cljs
- src/ethlance/ui/component/main_navigation_menu.cljs
- src/ethlance/ui/component/mobile_navigation_bar.cljs
- src/ethlance/ui/component/profile-image.cljs
- src/ethlance/ui/component/rating.cljs
- src/ethlance/ui/component/splash_layout.cljs
- src/ethlance/ui/component/splash_mobile_navigation_bar.cljs
- src/ethlance/ui/component/splash_navigation_bar.cljs
- src/ethlance/ui/config.cljs
- src/ethlance/ui/page/about.cljs
- src/ethlance/ui/page/how_it_works.cljs
- src/ethlance/ui/pages.cljs
- src/ethlance/ui/util/navigation.cljs
- Fixes #81 
- Added URL Routing utility functions
- Added About Page
- Added How it Works Page
- populated URLs for splash page and main layout component
- fixed URL resolution for icons to work with non-hash based URLs
> Added URL routing to pages

- resources/public/less/component/search-input.less
- src/ethlance/ui/component/search_input.cljs
- src/ethlance/ui/page/arbiters.cljs
- src/ethlance/ui/page/candidates.cljs
- src/ethlance/ui/page/jobs.cljs
- src/ethlance/ui/page/sign_up.cljs
- fixes #109 
- Additional work on pages to include auto suggestions and placeholders
> Minor improvements to chip search input

- resources/public/less/component/main-navigation-menu.less
- resources/public/less/component/mobile-navigation-bar.less
- src/ethlance/ui/component/main_navigation_menu.cljs
- src/ethlance/ui/component/mobile_navigation_bar.cljs
- Fixes #147 
- Also includes active navigated indicators for mobile navigation.
> Active url menu nav 147

- resources/public/less/base/box-shadow.less
- resources/public/less/component/button.less
- resources/public/less/component/currency-input.less
- resources/public/less/component/email-input.less
- resources/public/less/component/main-layout.less
- resources/public/less/component/search-input.less
- resources/public/less/component/select-input.less
- resources/public/less/component/splash-layout.less
- resources/public/less/component/tabular-layout.less
- resources/public/less/component/text-input.less
- resources/public/less/main.less
- resources/public/less/mixin/box-shadow.less
- resources/public/less/mixin/input.less
- resources/public/less/mixin/paper.less
- resources/public/less/mixins.less
- resources/public/less/page/arbiters.less
- resources/public/less/page/candidates.less
- resources/public/less/page/devcard.less
- resources/public/less/page/employers.less
- resources/public/less/page/jobs.less
- resources/public/less/page/me.less
- resources/public/less/page/profile.less
- src/ethlance/ui/component/text_input.cljs
- src/ethlance/ui/page/arbiters.cljs
- src/ethlance/ui/page/employers.cljs
- src/ethlance/ui/page/jobs.cljs
- src/ethlance/ui/page/sign_up.cljs
- Fixes issues with placeholders in text inputs
- Fixed color palettes so that primary --> light palette, secondary --> dark palette
- Added box-shadow mixin, applied to all places where box shadows are used
> Chrome url fix 129

- resources/public/less/page/arbiters.less
- resources/public/less/page/candidates.less
- resources/public/less/page/employers.less
- resources/public/less/page/jobs.less
- src/ethlance/ui/component/search_input.cljs
- src/ethlance/ui/page/arbiters.cljs
- src/ethlance/ui/page/candidates.cljs
- src/ethlance/ui/page/employers.cljs
- src/ethlance/ui/page/jobs.cljs
> Finished clickable tags #163

- resources/public/index.html
- resources/public/less/page/new-job.less
- src/ethlance/ui/component/radio_select.cljs
- src/ethlance/ui/page/new_job.cljs
> Fixed Button Styling, fixed checkbox svgs

- src/ethlance/shared/constants.cljs
- src/ethlance/ui/page/sign_up.cljs
> Added constant, fixed auto suggestiong

- src/ethlance/ui/component/currency_input.cljs
- src/ethlance/ui/page/sign_up.cljs
- Fixes #165 
- Currency input now uses 'number' type
> Fixed currency input to be numbers

- src/ethlance/ui/component/sign_in_dialog.cljs
- src/ethlance/ui/event/sign_in.cljs
- src/ethlance/ui/subscription/model.cljs
- `:sign-in` renamed to `:user/sign-in`
- `:sign-out` renamed to `:user/sign-out`
- intermediates also renamed
- removed erroneous file
> Sign in fixes 153

- resources/public/less/base/color.less
- resources/public/less/component/chat.less
- resources/public/less/component/main-navigation-menu.less
- resources/public/less/component/mobile-navigation-bar.less
- resources/public/less/component/select-input.less
- resources/public/less/mixin/input.less
- resources/public/less/page/arbiters.less
- resources/public/less/page/candidates.less
- resources/public/less/page/employers.less
- resources/public/less/page/invoice-detail.less
- resources/public/less/page/jobs.less
- resources/public/less/page/new-job.less
- src/ethlance/ui/component/icon.cljs
- src/ethlance/ui/component/search_input.cljs
- src/ethlance/ui/component/select_input.cljs
- src/ethlance/ui/component/splash_layout.cljs
- src/ethlance/ui/page/arbiters.cljs
- src/ethlance/ui/page/candidates.cljs
- src/ethlance/ui/page/employers.cljs
- src/ethlance/ui/page/invoice_detail.cljs
- src/ethlance/ui/page/job_contract.cljs
- src/ethlance/ui/page/jobs.cljs
- src/ethlance/ui/page/new_job.cljs
- Fixes #175 
- Fixes #186 
- Fixes #184 
- Fixes #185 
- Fixes #187 
- Fixes #183 
- Fixes #182 
- Fixes #181 
- Fixes #179
- Fixes #180 
- Fixes #178
> Christmas ui fixes 2019

- resources/public/less/base/media.less
- resources/public/less/component/main-layout.less
- resources/public/less/page/new-invoice.less
- resources/public/less/page/profile.less
- src/ethlance/ui/component/inline_svg.cljs
- src/ethlance/ui/component/search_input.cljs
- src/ethlance/ui/page/profile.cljs
- src/ethlance/ui/page/sign_up.cljs
- Fixes #176 
- Fixes #161, #145 
- Fixes #169 
- Fixes #167 
- Fixes #162
> New years eve fixes 19

- resources/public/index.html
- src/ethlance/ui/component/button.cljs
- src/ethlance/ui/component/ethlance_logo.cljs
- src/ethlance/ui/component/icon.cljs
- src/ethlance/ui/component/main_layout.cljs
- src/ethlance/ui/component/mobile_search_filter.cljs
- src/ethlance/ui/component/mobile_sidebar.cljs
- src/ethlance/ui/component/modal.cljs
- src/ethlance/ui/component/radio_select.cljs
- src/ethlance/ui/component/tag.cljs
- src/ethlance/ui/page/jobs.cljs
- src/ethlance/ui/util/component.cljs
> Fixed components to remove react key warnings, fixed other warnings

- resources/public/less/component/chat.less
- resources/public/less/component/radio-select.less
- resources/public/less/component/search-input.less
- resources/public/less/component/splash-layout.less
- resources/public/less/page/arbiters.less
- resources/public/less/page/candidates.less
- resources/public/less/page/employers.less
- resources/public/less/page/invoice-detail.less
- resources/public/less/page/job-detail.less
- resources/public/less/page/jobs.less
- src/ethlance/ui/component/chat.cljs
- src/ethlance/ui/component/mobile_navigation_bar.cljs
- src/ethlance/ui/page/arbiters.cljs
- src/ethlance/ui/page/invoice_detail.cljs
- src/ethlance/ui/page/new_job.cljs
low hanging fruit
- Fixes #198 
- Fixes #197 
- Fixes #195 
- Fixes #193 
- Fixes #187 
- Fixes #185 
- Fixes #184
> Jan 2020 fixes 1

- resources/public/less/component/main-navigation-menu.less
- resources/public/less/component/splash-navigation-bar.less
- src/ethlance/ui/component/splash_navigation_bar.cljs
- Fixes #194 
- Also fixes underline animation on splash page
> Animated main navigation menu elements, animated splash navigation

- resources/public/less/component/main-layout.less
- resources/public/less/page/invoice-detail.less
> Fixes layout issues with invoice detail page, and main layout fixes

- resources/public/less/component/main-layout.less
- resources/public/less/page/invoice-detail.less
- resources/public/less/page/new-invoice.less
> Fixed general main layout for mobile, fixed button and textarea

- resources/public/less/component/circle-button.less
- resources/public/less/component/tabular-layout.less
- src/ethlance/ui/component/circle_button.cljs
- src/ethlance/ui/page/me.cljs
> My activity fixes 206

- resources/public/less/component/button.less
- resources/public/less/component/select-input.less
- resources/public/less/component/tabular-layout.less
- resources/public/less/page/sign-up.less
- src/ethlance/ui/component/select_input.cljs
- src/ethlance/ui/page/sign_up.cljs
> Fixes for mobile sign up page

- project.clj
- resources/public/less/page/arbiters.less
> minor project file change, arbiter page fixes

- resources/public/less/page/arbiters.less
- resources/public/less/page/candidates.less
- resources/public/less/page/employers.less
- src/ethlance/ui/page/candidates.cljs
- src/ethlance/ui/page/employers.cljs
> Fixed candidates page for mobile, fixed employers page for mobile

- resources/public/less/page/jobs.less
- src/ethlance/ui/page/jobs.cljs
> Job page fixes

- resources/public/less/page/invoice-detail.less
- src/ethlance/ui/page/invoice_detail.cljs
- Fixes #224 
- Fixes Invoice Detail Styling
> Fixed Invoice Detail Styling

- resources/public/less/component/tabular-layout.less
- resources/public/less/mixin/box-shadow.less
- resources/public/less/page/sign-up.less
- src/ethlance/ui/component/splash_layout.cljs
- Fixes #221 
- Also updated copyright
> Fixed main box shadow, fixed copyright

- resources/public/less/base/layout.less
> Fixed href links visited styling

- project.clj
- resources/public/less/component/main-navigation-menu.less
- resources/public/less/page/me.less
- src/ethlance/shared/mock.cljs
- src/ethlance/ui/core.cljs
- src/ethlance/ui/event/job_listing.cljs
- src/ethlance/ui/events.cljs
- src/ethlance/ui/page/me.cljs
- src/ethlance/ui/page/me/events.cljs
- src/ethlance/ui/page/me/subscriptions.cljs
- src/ethlance/ui/subscriptions.cljs
- src/ethlance/ui/util/navigation.cljs
- Fixes #223 
- Adds initial re-frame fixes
- Increased transition duration for main navigation menu
> Fixed my activity underline animations, added initial re-frame page state

- resources/public/less/component/button.less
- resources/public/less/component/splash-layout.less
- src/ethlance/ui/component/splash_layout.cljs
- Fixes #220 
- Header Layout switched from flex to grid
- Added/Fixed figure for tablet/mobile
- Added/Fixed dialog circles for tablet/mobile
- Additional layout fixes
> Splash mobile styling fix 220

- package-lock.json
- project.clj
- src/ethlance/server/core.cljs
- src/ethlance/server/db.cljs
- src/ethlance/server/event_store.cljs
- src/ethlance/server/events_replay_system.cljs
- src/ethlance/server/graphql/authorization.cljs
- src/ethlance/server/graphql/middlewares.cljs
- src/ethlance/server/graphql/server.cljs
- src/ethlance/server/syncer.cljs
> Events replay system

- designs/Makefile
- resources/public/less/component/button.less
- resources/public/less/component/splash-layout.less
- src/ethlance/ui/component/splash_layout.cljs
- Fixes #219 
- Button Transition Effects have had their delays increased
- Fixes Button Styling of Footer
- More transition effects on footer
- Small makefile refactoring for ethlance design site
> Fixes Splash Footer Styling and Button Transitioning

- project.clj
- resources/public/less/component/splash-layout.less
- src/ethlance/ui/component/splash_layout.cljs
- Added React Transition Groups to ethlance
- Fixes #218, we can now apply this same library to all of our transition needs
> Added react-transition-group, Added Transitions to Splash Page

- resources/public/less/component/search-input.less
- src/ethlance/ui/component/search_input.cljs
Take a look at #109 for the screenshots of how it looks with this changes
> Fix #109 (Make Chip Search More Responsive)

- resources/public/less/component/splash-layout.less
- resources/public/less/page/home.less
- src/ethlance/ui/component/splash_layout.cljs
> A bunch of style fixes. Fixes #266, #265

- src/ethlance/ui/page/arbiters.cljs
- src/ethlance/ui/page/candidates.cljs
- src/ethlance/ui/page/jobs.cljs
> Fix #269 (Clicking on title should open detail page)

- resources/public/less/page/me.less
> Fix #267 My activity redundant shadow

- src/ethlance/ui/events.cljs
- src/ethlance/ui/graphql.cljs
- src/ethlance/ui/page/sign_up/events.cljs
- src/ethlance/ui/subscriptions.cljs
- src/ethlance/ui/util/component.cljs
Small code cleanup to make linter green & tests to run
> Cleanup some code to make Linter happy

- src/ethlance/server/db.cljs
- src/ethlance/server/graphql/resolvers.cljs
- src/ethlance/ui/page/profile.cljs
This will allow us to query users based on their rating in the future.
> Store ratings with user type

- .gitignore
- .tool-versions
- Makefile
- contracts/Ethlance.sol
- migrations/2_ethlance_contracts.js
- package.json
- server/package.json
- server/yarn.lock
- shadow-cljs.edn
- src/district/server/async_db.cljs
- src/ethlance/ui/component/main_layout.cljs
- src/ethlance/ui/component/pagination.cljs
- src/ethlance/ui/config.cljs
- src/ethlance/ui/core.cljs
- src/ethlance/ui/events.cljs
- src/ethlance/ui/page/new_job.cljs
- src/ethlance/ui/page/new_job/events.cljs
- src/ethlance/ui/subscription/utils.cljs
- src/tests/contract/ethlance_test.cljs
- src/tests/graphql/generator.cljs
- src/tests/graphql/resolvers_test.cljs
- src/tests/runner.cljs
- truffle.js
- ui/.tool-versions
- ui/package.json
- ui/yarn.lock
- yarn.lock
Ties up new job page http://d0x-vm:6500/jobs/new actions with calls to Ethlance.sol smart contract. This includes
- uploads to IPFS
- transactions to the Ethlance smart contract
- syncing of the state based on events in the Ethlance back-end
> New job page smart contract integration

- Procfile
- bb.edn
- server/src/ethlance/server/db.cljs
- server/src/ethlance/server/graphql/resolvers.cljs
- shared/src/ethlance/shared/graphql/schema.cljs
- shared/src/ethlance/shared/routes.cljs
- ui/deps.edn
- ui/src/ethlance/ui/graphql.cljs
- ui/src/ethlance/ui/page/job_detail.cljs
- ui/src/ethlance/ui/page/job_detail/subscriptions.cljs
- ui/src/ethlance/ui/page/jobs.cljs
- ui/src/ethlance/ui/page/jobs/events.cljs
- ui/src/ethlance/ui/page/jobs/graphql.cljs
- ui/src/ethlance/ui/page/jobs/subscriptions.cljs
- ui/src/ethlance/ui/page/new_job.cljs
- ui/src/ethlance/ui/page/profile.cljs
Job search page integration (front-end / back-end / db)
> Fix showing arbitration data on profile

- contracts/Job.sol
- scripts/server-repl-helpers.cljs
- server/deps.edn
- server/src/ethlance/server/core.cljs
- server/src/ethlance/server/db.cljs
- server/src/ethlance/server/graphql/resolvers.cljs
- server/src/ethlance/server/syncer.cljs
- shared/src/ethlance/shared/graphql/schema.cljs
- ui/deps.edn
- ui/src/ethlance/ui/events.cljs
- ui/src/ethlance/ui/page/invoices.cljs
- ui/src/ethlance/ui/page/invoices/events.cljs
- ui/src/ethlance/ui/page/job_contract.cljs
- ui/src/ethlance/ui/page/job_contract/events.cljs
- ui/src/ethlance/ui/page/job_contract/subscriptions.cljs
- ui/src/ethlance/ui/page/me.cljs
- ui/src/ethlance/ui/page/me/events.cljs
- ui/src/ethlance/ui/page/me/subscriptions.cljs
- ui/src/ethlance/ui/page/new_invoice/events.cljs
- ui/src/ethlance/ui/page/profile.cljs
- ui/src/ethlance/ui/page/profile/events.cljs
- ui/src/ethlance/ui/util/dates.cljs
> My activity page

- contracts/Job.sol
- server/src/ethlance/server/graphql/resolvers.cljs
- shared/src/ethlance/shared/graphql/schema.cljs
- ui/resources/public/less/component/table.less
- ui/src/ethlance/ui/component/info_message.cljs
- ui/src/ethlance/ui/component/table.cljs
- ui/src/ethlance/ui/page/job_contract.cljs
- ui/src/ethlance/ui/page/job_contract/events.cljs
- ui/src/ethlance/ui/page/jobs.cljs
- ui/src/ethlance/ui/page/me.cljs
- ui/src/ethlance/ui/page/me/events.cljs
- ui/src/ethlance/ui/page/new_invoice.cljs
- ui/src/ethlance/ui/page/new_job.cljs
- ui/src/ethlance/ui/page/profile.cljs
- ui/src/ethlance/ui/page/profile/events.cljs
- ui/src/ethlance/ui/page/profile/subscriptions.cljs
Whole table rows clickable links and they highlight on hover
[Screencast from 07-03-2023 08:08:31 AM.webm](https://github.com/district0x/ethlance/assets/674621/1a9b1792-8bda-470e-a5b6-f3e53b5cbef2)
> UI improvements

- contracts/Ethlance.sol
- contracts/Job.sol
- server/src/ethlance/server/core.cljs
- server/src/ethlance/server/db.cljs
- server/src/ethlance/server/graphql/resolvers.cljs
- server/src/ethlance/server/syncer.cljs
- server/src/tests/contract/job_test.cljs
- shared/src/ethlance/shared/graphql/schema.cljs
- ui/src/ethlance/ui/component/search_input.cljs
- ui/src/ethlance/ui/page/job_detail.cljs
- ui/src/ethlance/ui/page/job_detail/events.cljs
- ui/src/ethlance/ui/page/job_detail/subscriptions.cljs
- ui/src/ethlance/ui/page/me.cljs
- ui/src/ethlance/ui/util/navigation.cljs
[Screencast from 07-22-2023 01:21:13 PM.webm](https://github.com/district0x/ethlance/assets/674621/70928cd4-0cba-4934-bd63-a71c7174dd71)
> Implement ending jobs (returns funds for all contributors)

- server/src/tests/graphql/generator.cljs
- server/src/tests/graphql/resolvers_test.cljs
- ui/src/ethlance/ui/page/dev/contract_ops.cljs
> Add UI /dev/contract-ops to inspect app-db for debugging

- .circleci/config.yml
- .github/workflows/docker-image.yml
[comment]: # (Summarise the problem and how the pull request solves it. You can use github links)
...
Migrate all ci jobs to Github Actions workflow
Documentation changes
> Move workflow to github actions

- server/src/ethlance/server/syncer.cljs
sometimes, when websocket is disconnected, it comes an empty event. We ignore that not to break the server if that happens
> ignore event if empty

- .github/workflows/docker-image-prod.yml
- .github/workflows/docker-image-qa.yml
- .gitignore
- docker-builds/server/Dockerfile
- docker-builds/ui/Dockerfile
- docker-compose.yml
- ui/src/ethlance/ui/config.cljs
[comment]: # (Summarise the problem and how the pull request solves it. You can use github links)
...
Documentation changes
> Split and fix docker builds for qa and prod
